### ISSUE TITLE
Add content alert option

### ISSUE THREAD

**Issue by martijnende** [WeAreSeismica/seismica-ojs#8]
We should add a separate page providing our readers with various options for getting content updates. Things to add:

- RSS feeds (published articles and/or issues? Check "Web Feeds" OJS plugin)
- Newsletter
- Twitter / Facebook / Instagram

**Comment by ThomasLecocq** [comment]
This is the result of the default way: I've enable the Web Feed plugin on the test website, and then activated the "Web Feed" sidebar item :
Settings->Website->Appearance->Setup->Sidebar

![image](https://user-images.githubusercontent.com/916937/201469575-b7d7ed2a-4f37-4524-85a3-f1ef415dbb3e.png)

They can probably easily be made nicer using CSS :-)

**Comment by ThomasLecocq** [comment]
actually, just checked, the plugin is already enabled in the production site, it's only that the buttons are not shown, but this URL works, e.g. RSS2 : https://seismica.library.mcgill.ca/gateway/plugin/WebFeedGatewayPlugin/rss2

so for now I've added the links in the custom block that contains the Mailing List link:
![image](https://user-images.githubusercontent.com/916937/201469848-587e145c-d36e-40e6-bae5-cc8e8ed36564.png)

⚠️ in the configuration of the WebFeed **do not use** the "list N items", but well the "current issue" one, otherwise the NOT published items are returned too !!!
![image](https://user-images.githubusercontent.com/916937/201470091-88ce82d6-0647-42cb-a35d-9862c806d702.png)

**Comment by martijnende** [comment]
Ok, thanks Tom. Perhaps we shouldn't expand the sidebar for the time being, as we might risk drowning out content that we want people to notice. I'll close the issue for now.

**Comment by ThomasLecocq** [comment]
Agree!! Since these are simple links, we can also add them to the footer !
